### ISSUE TITLE
Node v4 required ?

### ISSUE THREAD

**Issue by sylvainlap** [wistityhq/strapi#3]
I made a fresh install of strapi (sudo npm install strapi -g), and strapi new test returns:
```
sylvainlap@CanHardXI:~/DEV/WORKSPACE$ strapi new test
/usr/bin/env: node --harmony: Aucun fichier ou dossier de ce type
```

However, my version of node is 0.12.7.

Is Strapi compatible with node v0.12 ? Or node v4 is required ?
If Node v4 is mandatory, you should add it in the README.

**Comment by loicsaintroch** [comment]
Strapi works fine on Node.js v0.12 and Node.js v4 is not mandatory.
We are still thinking about which version of Node.js we should advise... Node.js v4 is now the *default* Node.js version but a lot of developers are still on Node.js v0.12 and don't want to upgrade because of backward compatibilities.
We'll adapt very soon thanks to community feedback!

**Comment by sylvainlap** [comment]
This is my case, I don't want to update to node v4 for now because most of my projects are still in node v0.12.

However, I can't manage to run strapi new :/

**Comment by loicsaintroch** [comment]
Weird... Can you please create a new issue about this with the logs?
