### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by senikk** [wistityhq/strapi#56]
Feature request; making it possible to set default value in studio for a model field like boolean etc.

**Comment by Aurelsicoko** [comment]
@senikk: Thanks for your feedback! In my opinion, if we do that, we should extend your request to all sub attributes such as `autoIncrement`, `unique`, `index`, `primaryKey`, etc. However as you know, we're talking about moving to another ORM. That's why it's difficult to us to add this new feature in the Studio because those attributes are specific to Waterline.

**Comment by loicsaintroch** [comment]
Hey @senikk, sorry for the lack of communication this last few weeks-- but this was for a good reason. I have some interesting news regarding this issue.

We decided to split the Strapi stack in two different projects. Here is the reason:
- Strapi is and always will be a Node.js framework-- nothing more.
- The built-in features such as the Studio, the admin panel and the built-in APIs are not part of the framework as we call it. They are management features. Those features will be in another project will release soon.

The Strapi framework and the utils are for two different kind of users. This is why we decided to split the current ecosystem in two different projects. Don't worry: the built-in APIs and admin panel will still be open-source, even for the new project.

The Strapi v1.x.x will no longer be supported due to those changes and we'll encourage everyone to migrate to the v2. The migration process will be quick and smooth, easy as possible.

We'll soon write a blog post about our choices and why we unfortunately can't afford to support the v1 anymore, like we expected.

Since your issue concerns the Studio and not the framework, I decided to close it aiming to keep the issue tracker lean and focus on the framework only.

Also, your enhancement has been made in this new project, thanks a lot for your suggestion. :-)
