### ISSUE TITLE
ORM roadmap

### ISSUE THREAD

**Issue by akoudal** [wistityhq/strapi#58]
Hi,

First of all: great job! I've been exploring Strapi for the past few days, and so far I'm very impressed. 
I've been using it to prototype an API, and it was super easy to set up and plug in to my existing database. However I just saw in the documentation, that youre planning on switching to sequelize - are you planning on removing support for mongodb?

Happy new year,
Allan

**Comment by devinivy** [comment]
I'm also just generally curious why strapi has chosen to switch ORMs.

**Comment by dj-hedgehog** [comment]
@devinivy 
As @loicsaintroch said on the Slack #framework channel:

>Hey @channel! As you all know we currently use the Waterline ORM. Unfortunately, there is no more maintainers taking care of it, both the core and the adapters... So, we definitely need to change the ORM since most of the issues we encounteer on Strapi are due to Waterline. We really need to know: which DBs do you use? What ORM do you like and why?

Please join the Strapi Slack instance for such questions at http://slack.strapi.io/

**Comment by loicsaintroch** [comment]
Hey!

Sorry for the lack of communication those last few days— we were just enjoying holidays. Time to get back to work!

First of all, Strapi needs a production-ready ORM which is not the case of Waterline mainly because adapters are too unstable and not well maintained to make a stable product like we need. We can’t give an all-in-one stack with some bugs coming from a dependency. If you take a look at our issues almost all of them are due to Waterline.

Also, every NoSQL database has its own use and specific features. For example, an admin panel can’t really interact the same way with a MySQL database than with a Neo4j database. We can’t take advantage of every NoSQL database specialties. NoSQL is good but for specific use. This is not our case.

Strapi uses more and more relations as long as you follow the conventional structure. That’s why a SQL ORM is more appropriate. The main Node.js SQL ORMs are Sequelize and Bookshelf. The both of them have pros and cons. We still don’t know which one to use. I personally prefer Bookshelf for its approach using the Knex query builder and the “Rails-like” structure but Sequelize “seems” more stable— need feedback here.

We thought about being ORM agnostic which is technically great. Unfortunately this is not our philosophy since we want an all-in-one stack— we can call it a Data Management Framework. If we support several ORMs we won’t be able to have a marketplace since every item won’t have the same structure. However, you’ll still be able to use your own ORM on your side but the Studio won’t work with it. We’ll only support the official ORM used by the Strapi framework.

To finally answer your question: we won’t officially support MongoDB as a database but you’ll still be able to use it on your own. The user management and the Studio won’t be compatible with it since it’s developed to only work with the official supported ORM.

I hope I answered your question but I let the issue open since we really want/need feedback on this.

Thank you for your question @akoudal.

**Comment by akoudal** [comment]
Thanks for the detailed answer - it definitely answered my question. 

Bad news for me, as the studio API generator and user management is brilliant. 
I'll definitely keep this project on the radar, and get back if I do a sql project. 

Cheers,
Allan

**Comment by loicsaintroch** [comment]
We give some thoughts about the ORM roadmap and put it some work.

I have a very early prototype of Strapi working both with Waterline and Bookshelf without changing the models at all. So we definitely can make this work with Mongoose or whatever on the framework. However, we'll need to make it right on the Studio regarding the UX on the settings page. 

I don't want to rush anything here but if it works correctly with Bookshelf and Waterline I don't see why we won't make a Mongoose hook and support it on the Studio since we don't need to change the model definitions. 

As I said, don't take my word as a final decision but more as a possibility.

**Comment by TylerGarlick** [comment]
I kind of like the approach of waterline honestly. I rarely use a SQL database these days with my apis, and I would rather see a data storage agnostic approach with squelize or orm "x" as the default. As long as I'm not pinned to a particular implementation, I think it would be most beneficial.  

I'd be happy to help if you'd like to collaborate with your ideas.

**Comment by devinivy** [comment]
There's another adapter based ORM named Firenze which looks nice, but does not support associations in the way Waterline does.  It's a young project, and not heavily "featured".

**Comment by TylerGarlick** [comment]
What's the beef with waterline?

**Comment by TylerGarlick** [comment]
I've used this one before it was quite pleasant. http://www.camintejs.com/en

**Comment by loicsaintroch** [comment]
We'll use Bookshelf with Knex as the default ORM but you'll be able pull it out since it won't be part of the Strapi core. This way, you can move to another ORM like Waterline. Here are the repos (empty for now):

- https://github.com/wistityhq/strapi-bookshelf
- https://github.com/wistityhq/strapi-waterline

**Comment by TylerGarlick** [comment]
Is the plan to then support these orm's via a plugin interface?

**Comment by loicsaintroch** [comment]
We'll support several ORMs via the hook system. The Strapi core will require mandatory ORMs for the models thanks to `orm` key in each model.

**Comment by TylerGarlick** [comment]
Seems reasonable to me...

**Comment by loicsaintroch** [comment]
We decided to support several ORMs aiming to allow you to use other DBs such as MongoDB, ArangoDB, Redis, etc. if you have specific needs.

**Comment by akoudal** [comment]
Awesome
