### ISSUE TITLE
Not able to start the project

### ISSUE THREAD

**Issue by hguillermo** [wistityhq/strapi#61]
I was adding relations in the Studio then I tried to restart the local app and now I am getting this:

warn: Setting the migrate strategy of the `companies` model to `alter`.

The app doesn't start and the studio won't connect. Is there a way to delete these relations manually?

**Comment by phudekar** [comment]
I am facing the same problem. App is stuck at 
`warn: Setting the migrate strategy of the car model to alter`

I am running Strapi on `Mac OS X El Capitan 10.11.3` `node v5.2.0 ` and `npm 3.3.12`

**Comment by loicsaintroch** [comment]
Hey @hguillermo and @phudekar, sorry for the lack of communication this last few weeks-- but this was for a good reason. I have some interesting news regarding this issue.

We decided to split the Strapi stack in two different projects. Here is the reason:
- Strapi is and always will be a Node.js framework-- nothing more.
- The built-in features such as the Studio, the admin panel and the built-in APIs are not part of the framework as we call it. They are management features. Those features will be in another project will release soon.

The Strapi framework and the utils are for two different kind of users. This is why we decided to split the current ecosystem in two different projects. Don't worry: the built-in APIs and admin panel will still be open-source, even for the new project.

The Strapi v1.x.x will no longer be supported due to those changes and we'll encourage everyone to migrate to the v2. The migration process will be quick and smooth, easy as possible.

We'll soon write a blog post about our choices and why we unfortunately can't afford to support the v1 anymore, like we expected.

Since your issue concerns the Waterline ORM used in v1 and the Studio, I decided to close it aiming to keep the issue tracker lean and focus on the framework only.

Also, since you are moving from Waterline to Knex / Bookshelf your issue has been fixed in this new version, thanks a lot for your feedback. :-)
