### ISSUE TITLE
strapi local dev server crash after strapi start

### ISSUE THREAD

**Issue by shilka** [wistityhq/strapi#62]
I has made some changes in my studio account, which was i belive disabling graphql, adding api prefix and maybe something else, then back to my terminal and saw this:

```
info: Application's dictionnary updated
warn: You still need to restart your server to fully enjoy changes...
error: The connection `undefined` specified in the `email` model does not exist.
```

and then ```$ strapi start``` don't start the application throwing

```
/home/shilkovsky/.npm-packages/lib/node_modules/strapi/lib/configuration/hooks/_api/index.js:168
          strapi.config.routes = _.merge(strapi.config.routes, strapi.api[api.name].config.routes);
                                                                                          ^

TypeError: Cannot read property 'routes' of undefined
    at /home/shilkovsky/.npm-packages/lib/node_modules/strapi/lib/configuration/hooks/_api/index.js:168:91
    at /home/shilkovsky/.npm-packages/lib/node_modules/strapi/node_modules/async/lib/async.js:52:16
    at /home/shilkovsky/.npm-packages/lib/node_modules/strapi/node_modules/async/lib/async.js:550:17
    at /home/shilkovsky/.npm-packages/lib/node_modules/strapi/node_modules/async/lib/async.js:544:17
    at _arrayEach (/home/shilkovsky/.npm-packages/lib/node_modules/strapi/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/home/shilkovsky/.npm-packages/lib/node_modules/strapi/node_modules/async/lib/async.js:543:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Is there any way I can fix this?

**Comment by shilka** [comment]
Ok, i have played with config and now I know that deleting a default permanent storage from the interface was not a good idea :) The steps reproducing this are:
1. go to http://studio.strapi.io/#!/settings/database
2. delete all the items
I belive the interface should block the actions that brings to crash, or at least give some warnings. This will prevent destroying own apps by monkeys that clicks around to all buttons, that they see, like me.

**Comment by Karnith** [comment]
What would be nice for this is to be able to specify the database type verses needing to manually update the connections in the config.

**Comment by loicsaintroch** [comment]
If I understand correctly the issue here we need to prevent the user to remove used connections right?

**Comment by shilka** [comment]
That would definitely resolve my issue.

**Comment by loicsaintroch** [comment]
Looks pretty obvious yes-- but yet it appears we didn't do it...

**Comment by shilka** [comment]
Since you know about the issue, I can live with this. If there is some sort of trouble making a code change I suggest to put a warning, that removing current connection can lead to crash. That could do the job.

**Comment by loicsaintroch** [comment]
Thanks. We'll definitely developed the verification process for the v2! Keeping this issue open until this is not done.

**Comment by loicsaintroch** [comment]
Hey @shilka, sorry for the lack of communication this last few weeks-- but this was for a good reason. I have some interesting news regarding this issue.

We decided to split the Strapi stack in two different projects. Here is the reason:
- Strapi is and always will be a Node.js framework-- nothing more.
- The built-in features such as the Studio, the admin panel and the built-in APIs are not part of the framework as we call it. They are management features. Those features will be in another project will release soon.

The Strapi framework and the utils are for two different kind of users. This is why we decided to split the current ecosystem in two different projects. Don't worry: the built-in APIs and admin panel will still be open-source, even for the new project.

The Strapi v1.x.x will no longer be supported due to those changes and we'll encourage everyone to migrate to the v2. The migration process will be quick and smooth, easy as possible.

We'll soon write a blog post about our choices and why we unfortunately can't afford to support the v1 anymore, like we expected.

Since your issue concerns the Studio, I decided to close it aiming to keep the issue tracker lean and focus on the framework only.

Also, your issue has been fixed in this new project, thanks a lot for your suggestion. :-)
