### ISSUE TITLE
Add autocomplete=off attribute to the studio

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#74]
When I go to database settings page in studio, my browser automatically fill fields "username" and "password". Maybe you can add attribute `autocomplete="off"` in these fields?

![2016-01-31 22 35 48](https://cloud.githubusercontent.com/assets/557190/12704394/1df1d3d4-c86b-11e5-9c47-39efc962d7dd.png)

Browser: Google Chrome, Mac OS.

**Comment by Aurelsicoko** [comment]
Totally agree! Furthermore with an email address in the "username" field that can provoke some bugs during the server start.

**Comment by loicsaintroch** [comment]
Hey @kulakowka, sorry for the lack of communication this last few weeks-- but this was for a good reason. I have some interesting news regarding this issue.

We decided to split the Strapi stack in two different projects. Here is the reason:
- Strapi is and always will be a Node.js framework-- nothing more.
- The built-in features such as the Studio, the admin panel and the built-in APIs are not part of the framework as we call it. They are management features. Those features will be in another project will release soon.

The Strapi framework and the utils are for two different kind of users. This is why we decided to split the current ecosystem in two different projects. Don't worry: the built-in APIs and admin panel will still be open-source, even for the new project.

The Strapi v1.x.x will no longer be supported due to those changes and we'll encourage everyone to migrate to the v2. The migration process will be quick and smooth, easy as possible.

We'll soon write a blog post about our choices and why we unfortunately can't afford to support the v1 anymore, like we expected.

Since your issue concerns the Studio and not the framework, I decided to close it aiming to keep the issue tracker lean and focus on the framework only.

Also, your enhancement has been made in this new project, thanks a lot for your suggestion. :-)
