### ISSUE TITLE
Admin panel is not working correctly when population is disabled.

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#77]
When I turn off the population in the application settings.

![2016-02-01 1 40 54](https://cloud.githubusercontent.com/assets/557190/12705558/dcd21c64-c884-11e5-82b7-5b59f082f868.png)

The administrator panel ceases to function properly. In the list does not appear related models (createdBy, updatedBy, etc..)

![2016-02-01 1 41 57](https://cloud.githubusercontent.com/assets/557190/12705567/00cc1bc4-c885-11e5-9999-e38c71fa887e.png)

In editing page a related models is not displayed, too.

![2016-02-01 1 44 47](https://cloud.githubusercontent.com/assets/557190/12705583/653d41f0-c885-11e5-8546-ec251a5ad902.png)

But when I turn population back - it's worked correctly.

![2016-02-01 1 46 09](https://cloud.githubusercontent.com/assets/557190/12705592/96ccd1b8-c885-11e5-96d1-5be0a5cbdb83.png)

Now the list looks like this:

![2016-02-01 1 46 28](https://cloud.githubusercontent.com/assets/557190/12705595/ac855912-c885-11e5-81a5-b93a72a708e5.png)

On the edit page also works.

![2016-02-01 1 48 03](https://cloud.githubusercontent.com/assets/557190/12705607/da58de4a-c885-11e5-8d65-c44244040d73.png)

You may want to enable forced population to administration panel?

**Comment by loicsaintroch** [comment]
Hey @kulakowka, sorry for the lack of communication this last few weeks-- but this was for a good reason. I have some interesting news regarding this issue.

We decided to split the Strapi stack in two different projects. Here is the reason:
- Strapi is and always will be a Node.js framework-- nothing more.
- The built-in features such as the Studio, the admin panel and the built-in APIs are not part of the framework as we call it. They are management features. Those features will be in another project will release soon.

The Strapi framework and the utils are for two different kind of users. This is why we decided to split the current ecosystem in two different projects. Don't worry: the built-in APIs and admin panel will still be open-source, even for the new project.

The Strapi v1.x.x will no longer be supported due to those changes and we'll encourage everyone to migrate to the v2. The migration process will be quick and smooth, easy as possible.

We'll soon write a blog post about our choices and why we unfortunately can't afford to support the v1 anymore, like we expected.

Since your issue concerns the admin panel and not the framework, I decided to close it aiming to keep the issue tracker lean and focus on the framework only.

Also, your enhancement has been made in this new project, thanks a lot for your suggestion. :-)
