### ISSUE TITLE
Promise.defer(); is obsolete

### ISSUE THREAD

**Issue by sylvainlap** [wistityhq/strapi#80]
In your code, you use `const deferred = Promise.defer();` to create a new Promise. According to https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Deferred this method is obsolete.

You should use the ES6 way: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

```
new Promise(function(resolve, reject) {
  if (ok) {
    resolve();
  } else {
    reject();
  }
});
```

**Comment by Aurelsicoko** [comment]
@sylvainlap I also read that the Promise constructor is throw safety. I don't know why we used the common deferred anti-pattern... This is a good timing because we have to rewrite the generators to consider our move to Bookshelf.

**Comment by loicsaintroch** [comment]
Hey @sylvainlap, sorry for the lack of communication this last few weeks-- but this was for a good reason. I have some interesting news regarding this issue.

We decided to split the Strapi stack in two different projects. Here is the reason:
- Strapi is and always will be a Node.js framework-- nothing more.
- The built-in features such as the Studio, the admin panel and the built-in APIs are not part of the framework as we call it. They are management features. Those features will be in another project will release soon.

The Strapi framework and the utils are for two different kind of users. This is why we decided to split the current ecosystem in two different projects. Don't worry: the built-in APIs and admin panel will still be open-source, even for the new project.

The Strapi v1.x.x will no longer be supported due to those changes and we'll encourage everyone to migrate to the v2. The migration process will be quick and smooth, easy as possible.

We'll soon write a blog post about our choices and why we unfortunately can't afford to support the v1 anymore, like we expected.

Since your issue concerns the built-in APIs and not the framework, I decided to close it aiming to keep the issue tracker lean and focus on the framework only.

Also, your enhancement has been made in this new project, thanks a lot for your suggestion. :-)
