### ISSUE TITLE
What about GraphiQL?

### ISSUE THREAD

**Issue by kulakowka** [wistityhq/strapi#81]
Hi guys!

What do you think about [GraphiQL](https://github.com/graphql/graphiql)? 

GraphiQL - An in-browser IDE for exploring GraphQL. [Try the live demo](http://graphql-swapi.parseapp.com/).

![](https://github.com/graphql/graphiql/raw/master/resources/graphiql.png)

Maybe you can add it to the admin panel?
or it can be added as a separate url available only to administrators.

Maybe it will help you. There is a plugin for koa: [koa-graphiql](https://github.com/exponentjs/koa-graphiql)

**Comment by loicsaintroch** [comment]
Hey @kulakowka. We tried GraphiQL a few months ago when developed the GraphQL support for Strapi. This is not a priority at all for us since this is an existing and open-source feature already out there. If one day we think it can be useful and become a priority for us we'll definitely do it! Thanks for the suggestion though. :-)
