### ISSUE TITLE
Critical Bug: Creating nested models fails

### ISSUE THREAD

**Issue by mraak** [wistityhq/strapi#86]
1. Go to Studio and create an API - Category
2. Create a field 'name'
3. Create a relationship 'parent', and select Category as API for linking. Select many-to-one relationship. 
4. Now go to your admin > models > Categories, and try to create a model.

You get the following error in the browser but no in the console. The operation fails. 

```
TypeError: Cannot read property 'id' of null
    at h.w [as hideDeleteButton] (http://localhost:1337/admin/frontend.min.js:1:20056)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:1337/admin/vendors.min.js:4:20776), <anonymous>:4:458)
    at h.$digest (http://localhost:1337/admin/vendors.min.js:3:4651)
    at http://localhost:1337/admin/vendors.min.js:3:6107
    at i (http://localhost:1337/admin/vendors.min.js:1:21413)
    at http://localhost:1337/admin/vendors.min.js:1:22867(anonymous function) @ vendors.min.js:2
5http://localhost:1337/api/admin/explorer/pollcategory Failed to load resource: the server responded with a status of 400 (Bad Request)

```

This is of course a showstopper for loads of different projects.

**Comment by loicsaintroch** [comment]
Hey @mraak, sorry for the lack of communication this last few weeks-- but this was for a good reason. I have some interesting news regarding this issue.

We decided to split the Strapi stack in two different projects. Here is the reason:
- Strapi is and always will be a Node.js framework-- nothing more.
- The built-in features such as the Studio, the admin panel and the built-in APIs are not part of the framework as we call it. They are management features. Those features will be in another project will release soon.

The Strapi framework and the utils are for two different kind of users. This is why we decided to split the current ecosystem in two different projects. Don't worry: the built-in APIs and admin panel will still be open-source, even for the new project.

The Strapi v1.x.x will no longer be supported due to those changes and we'll encourage everyone to migrate to the v2. The migration process will be quick and smooth, easy as possible.

We'll soon write a blog post about our choices and why we unfortunately can't afford to support the v1 anymore, like we expected.

Since your issue concerns the Studio, the admin panel and the Waterline ORM but not the framework, I decided to close it aiming to keep the issue tracker lean and focus on the framework only. The Waterline ORM won't be used anymore, we decided to switch to Knex / Bookshelf for the v2 for some very good reasons.

Thanks a lot for your feedback though we appreciate your help on this project. :-)
