### ISSUE TITLE
Strapi Studio drop down list doesn't show all options

### ISSUE THREAD

**Issue by chewedon** [wistityhq/strapi#92]
Hey guys, just testing Strapi and Strapi Studio.

I've created Pokemon and Poketypes so far.

A Pokemon can have many Poketypes and each Poketype can have belong to many Pokemons, so a Many-To-Many relationship. 

I created all the Poketypes first such as Grass, Fire, Water, Electric etc.

Then when I went to create the first Pokemon called Bulbasaur (http://www.pokemon.com/us/pokedex/bulbasaur) who is Grass and Poison type, I could not pick Grass and Poison from the relation drop down list:

![screen shot 2016-02-24 at 12 47 07 pm](https://cloud.githubusercontent.com/assets/1171355/13275950/60c102ce-daf5-11e5-9678-f3176db4ad2c.png)

![screen shot 2016-02-24 at 12 47 19 pm](https://cloud.githubusercontent.com/assets/1171355/13275952/6dd2a8b4-daf5-11e5-9e70-d29b5bfafa33.png)

As you can see from the two screenshots above, Grass and Poison are not in the list.

The work around is for me to choose a few of the ones that are shown in the list until Grass and Poison show up. I choose Grass and Poison, then I delete the ones that I temporarily selected earlier.

Hopefully this hasn't been asked before, if it has, please mark duplicate and delete/close this issue.

**Comment by loicsaintroch** [comment]
Hey @chewedon, sorry for the lack of communication this last few weeks-- but this was for a good reason. I have some interesting news regarding this issue.

We decided to split the Strapi stack in two different projects. Here is the reason:
- Strapi is and always will be a Node.js framework-- nothing more.
- The built-in features such as the Studio, the admin panel and the built-in APIs are not part of the framework as we call it. They are management features. Those features will be in another project will release soon.

The Strapi framework and the utils are for two different kind of users. This is why we decided to split the current ecosystem in two different projects. Don't worry: the built-in APIs and admin panel will still be open-source, even for the new project.

The Strapi v1.x.x will no longer be supported due to those changes and we'll encourage everyone to migrate to the v2. The migration process will be quick and smooth, easy as possible.

We'll soon write a blog post about our choices and why we unfortunately can't afford to support the v1 anymore, like we expected.

Since your issue concerns the admin panel and not the framework, I decided to close it aiming to keep the issue tracker lean and focus on the framework only.

Also, your issue has been fixed in this new project, thanks a lot for your suggestion. :-)
