### ISSUE TITLE
I cant found information, how to create studio key and link is outdated

### ISSUE THREAD

**Issue by PetrSnobelt** [wistityhq/strapi#99]
Link from studio to http://dashboard.strapi.io/#!/settings/security don't work

**Comment by loicsaintroch** [comment]
Hey @PetrSnobelt. What was your steps? Did you try to connect to the Studio on http://studio.strapi.io/ ?

**Comment by PetrSnobelt** [comment]
I connect to http://studio.strapi.io/ then click on help button and try use link from this sentence "Follow those steps and set your secret key in your application."

**Comment by loicsaintroch** [comment]
Looks like you find an easter egg... The actual link is http://studio.strapi.io/#!/settings/security.

**Comment by PetrSnobelt** [comment]
When I try it > popup error "You don't have application"

**Comment by loicsaintroch** [comment]
Well yes you need to create an app first. Please follow the steps and everything will work smoothly. :-)

**Comment by PetrSnobelt** [comment]
I create app - but because I don't install strapi globaly (which I don't like) it ends with error..

I simply don't know hwat ot put in "secretKey": "YOUR SECRET KEY HERE"
I try my own text, but it don't work

**Comment by loicsaintroch** [comment]
Oh I see... That's not the behavior we expect.

1. You need to create a `POST` request to `http://studio.strapi.io/auth/local` with cURL for example with your email address as `identifier` and your `password`.
2. Then, create a `.strapirc` file at `$HOME` with the `token` previously received from the Studio during the first step.
3. Make a `POST` request to `http://studio.strapi.io/app` with cURL for example with the `name` of your application and your `token`.
4. Finally, write the `appId` you received in your `./config/studio.json` file.

Honestly, this is a nightmare because of security process. This is why there is the Strapi CLI, to make it simple.

**Comment by PetrSnobelt** [comment]
OK, thank you for clarification. 
Maybe little form with appid textbox and generate button which generate json can be usefull in studio UI...

**Comment by loicsaintroch** [comment]
We'll think about it and see this is something we need. Thanks for your feedback.
